.PHONY: clean All

All:
	@echo "----------Building project:[ for_loop - Debug ]----------"
	@cd "for_loop" && "$(MAKE)" -f  "for_loop.mk"
clean:
	@echo "----------Cleaning project:[ for_loop - Debug ]----------"
	@cd "for_loop" && "$(MAKE)" -f  "for_loop.mk" clean
