.PHONY: clean All

All:
	@echo "----------Building project:[ First_program - Debug ]----------"
	@cd "D:\Edu\CodeLite_WorkSpace\section5\First_program" && "$(MAKE)" -f  "First_program.mk"
clean:
	@echo "----------Cleaning project:[ First_program - Debug ]----------"
	@cd "D:\Edu\CodeLite_WorkSpace\section5\First_program" && "$(MAKE)" -f  "First_program.mk" clean
