.PHONY: clean All

All:
	@echo "----------Building project:[ C_style_String - Debug ]----------"
	@cd "C_style_String" && "$(MAKE)" -f  "C_style_String.mk"
clean:
	@echo "----------Cleaning project:[ C_style_String - Debug ]----------"
	@cd "C_style_String" && "$(MAKE)" -f  "C_style_String.mk" clean
